### ISSUE TITLE
アセットパイプラインが動作しない

### ISSUE THREAD

**Issue by rainwont** [rainwont/projects#13]
動作していない。

**Comment by kmaeda-toys** [comment]
エラー文等を載せましょう。後で見返した時、参考になる
(2ch、知恵袋とか質問する体でやるといいです）

**Comment by rainwont** [comment]
アセット・パイプラインの動作確認

環境変数を本番モードに変更
set RAILS_ENV=production

rake assets:precompile

config/environments/production.rbの
config.serve_static_assets を　false から true　に変更

rake db:create
 db/development.sqlite3 already exists
 db/test.sqlite3 already exists

上記でRAILS_ENV=production に環境変数を変えたが、db/development.sqlite3が既にあるとエラー。
db/production.sqlite3に変わってないとおかしいと思う。

rake db:migrate
rails server 

ブラウザでページを表示し、HTMLソースを確認したが、CSSファイルとJavascriptファイルへのリンクがまとめられていない。

**Comment by rainwont** [comment]
誤解していた。
HTMLソースではなくて、public/assetsフォルダにファイルが生成させるだけなのか。

application-a8181bad60bb4de55d81a2b9f7689665.css
application-a8181bad60bb4de55d81a2b9f7689665.css.gz
application-dcd7535fa2c53dd59c215d0a25caed29.css
application-dcd7535fa2c53dd59c215d0a25caed29.css.gz
application-e015abf3ca372368e6272399cbea6bee.js
application-e015abf3ca372368e6272399cbea6bee.js.gz
logo-67a1b342cce4140b8b41eb1b5272986e.gif
manifest-ce192c32c96064ff0006dfec134097bc.json
rails-1b894cd727cbbd0ac7d455b0c335e41e.png

**Comment by rainwont** [comment]
環境変数を本番モードに変更
export RAILS_ENV=production

set を　export にしたら直った。Windowsならsetだけど、Linuxではexportを使う。
